[workspace]
members = ["examples", "benckmark", "design-pattern"]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
chrono = "0.4.38"
cursive = "0.20.0"
nom = "7.1.3"
bytes = "1.6.1"
dateparser = "0.2.1"
regex = "1.10.5"
