[package]
name = "benckmark"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[dependencies.examples]
path = "../examples"

[[bench]]
name = "parser_benchmark"
path = "benches/benchmark.rs"
harness = false
